version: '3'
services:
  vendor-profile-management:
    image: chaengsaltz/tt-vendor-profile-management:latest
    container_name: vendor-profile-management
    ports:
      - "8002:8002"
    depends_on:
      - postgres_vendor_profile_management
    environment:
      - POSTGRES_HOST=postgres_vendor_profile_management
      - POSTGRES_PORT=5432
      - POSTGRES_USER=vendor
      - POSTGRES_PASSWORD=vendor_password
      - POSTGRES_DB=vendor

  postgres_vendor_profile_management:
    image: postgres:16
    container_name: postgres_vendor_profile_management
    environment:
      - POSTGRES_DB=vendor
      - POSTGRES_USER=vendor
      - POSTGRES_PASSWORD=vendor_password
    volumes:
      - postgres_vendor_profile_management_data:/var/lib/postgresql/vendor_data

volumes:
  postgres_vendor_profile_management_data: